CREATE TABLE MY_BADGE_RE_FEED 
(	
    LOGIN VARCHAR2(256 CHAR), 
    EMPLID VARCHAR2(256 CHAR)
);

INSERT INTO MY_BADGE_RE_FEED (LOGIN, EMPLID) VALUES ('JPROUDMOORE','100000');
INSERT INTO MY_BADGE_RE_FEED (LOGIN, EMPLID) VALUES ('AWINDRUNNER','100001');
INSERT INTO MY_BADGE_RE_FEED (LOGIN, EMPLID) VALUES ('MSTORMRAGE','100002');